# Generated by Django 5.2.3 on 2025-06-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psrrtech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address_line_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
