# Generated by Django 5.2.3 on 2025-06-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psrrtech', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='pan_number',
            new_name='tax_id',
        ),
    ]
