# Generated by Django 5.2.3 on 2025-06-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psrrtech', '0005_rename_pan_number_employee_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address_line_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('ADMIN', 'Administration'), ('HR', 'Human Resources'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('FULL-TIME', 'Full-Time'), ('PADRT-TIME', 'Part-Time')], default='FULL_TIME', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_photos/'),
        ),
    ]
